- task: AzureFunctionApp@1
  inputs:
    azureSubscription: 'doh-sub-vaccs-01 (c47773b2-99d9-4614-8b2c-737ab9ec3e73)-1813'
    appType: 'functionApp'
    appName: 'fa-waverify-qrc-dev'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    deploymentMethod: 'auto'